logo-image: 'img/logo.png'

phonenumber: '123 456 789'
email: 'hola@mybrand.com'


icontwitter: '#'
iconpinterest: '#'
iconlinkedin: '#'
iconflickr: '#'
iconvimeo: '#'
iconyoutube: '#'


nav:
  -
    name: "Home"
    actual: "true"
  -
    name: "Products"
  -
    name: "Gallery"
  -
    name: "News"
  -
    name: "Contact"
